# Generated by Django 5.2.5 on 2025-08-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_profiladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profillivreur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='livreurs/', verbose_name='Photo'),
        ),
    ]
