# Generated by Django 5.2.5 on 2025-08-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_profillivreur_photo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE boutique_produit DROP COLUMN IF EXISTS image_url;",
                    reverse_sql="ALTER TABLE boutique_produit ADD COLUMN IF NOT EXISTS image_url varchar(200);",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='produit',
                    name='image_url',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE boutique_produit ADD COLUMN IF NOT EXISTS image varchar(100);",
                    reverse_sql="ALTER TABLE boutique_produit DROP COLUMN IF EXISTS image;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='produit',
                    name='image',
                    field=models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image'),
                ),
            ],
        ),
    ]
