# Generated by Django 5.2.5 on 2025-08-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_remove_produit_image_url_produit_image'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE boutique_produit DROP COLUMN IF EXISTS image_url;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[],
        ),
    ]
