# Generated by Django 5.2.5 on 2025-08-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_remove_produit_image_url'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE boutique_produit ADD COLUMN IF NOT EXISTS image varchar(100);",
                    reverse_sql="ALTER TABLE boutique_produit DROP COLUMN IF EXISTS image;",
                ),
            ],
            state_operations=[],
        ),
    ]
