# Generated by Cascade to add checkout/payment fields on Commande
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boutique', '0006_produit_image'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE boutique_commande "
                        "ADD COLUMN IF NOT EXISTS nom_complet varchar(150) NOT NULL DEFAULT '';"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE boutique_commande "
                        "ADD COLUMN IF NOT EXISTS telephone varchar(30) NOT NULL DEFAULT '';"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE boutique_commande "
                        "ADD COLUMN IF NOT EXISTS ville varchar(100);"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE boutique_commande "
                        "ADD COLUMN IF NOT EXISTS payment_method varchar(10);"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE boutique_commande "
                        "ADD COLUMN IF NOT EXISTS payment_status varchar(10) NOT NULL DEFAULT 'pending';"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='commande',
                    name='nom_complet',
                    field=models.CharField(max_length=150, verbose_name='Nom complet', default=''),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='commande',
                    name='telephone',
                    field=models.CharField(max_length=30, verbose_name='Téléphone', default=''),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='commande',
                    name='ville',
                    field=models.CharField(max_length=100, verbose_name='Ville', blank=True, default=''),
                ),
                migrations.AddField(
                    model_name='commande',
                    name='payment_method',
                    field=models.CharField(max_length=10, verbose_name='Moyen de paiement', choices=[('tmoney','TMoney'),('flooz','Flooz')], null=True, blank=True),
                ),
                migrations.AddField(
                    model_name='commande',
                    name='payment_status',
                    field=models.CharField(max_length=10, verbose_name='Statut paiement', choices=[('pending','En attente de paiement'),('paid','Payé'),('failed','Échoué')], default='pending'),
                ),
            ],
        ),
    ]
