# Generated by Django 5.2.5 on 2025-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_commande_checkout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
    ]
