# Generated by Django 5.1.3 on 2025-11-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profillivreur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='numero_cni',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Numéro CNI'),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier'),
        ),
    ]
